version: "3"

services:
  fastapi:
    build: ./
    command: uvicorn app.main:app --port 8772 --host 0.0.0.0 --reload
    container_name: fastapi-application-test
    volumes:
      - ./app:/app
    ports:
      - "8772:8772"
volumes:
  app: